// <auto-generated />
namespace Shoppi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedtypesforproductandremovedproductquantityitisintypesnow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedtypesforproductandremovedproductquantityitisintypesnow));
        
        string IMigrationMetadata.Id
        {
            get { return "201708312203165_Added types for product and removed product quantity (it is in types now)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
