// <auto-generated />
namespace Shoppi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Priceforproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Priceforproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201708102221023_Price for product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
