// <auto-generated />
namespace Shoppi.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenamingTypeNametoTypeLabel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamingTypeNametoTypeLabel));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041512258_Renaming TypeName to TypeLabel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
